#' Plot leaflet choropleth
#' 
#' @description Plot interactive choropleth using leaflet with a simplified theme designed for 
#' improved appearance in the absence of background tiles. The theme requires pitoolbox to be 
#' installed locally. **NOTE**: if you would like to use the embedded `crosstalk` functionality of
#' [plot_leaflet()], 
#' [you *must* install a patched version of leaflet](https://github.com/rstudio/leaflet/pull/499) 
#' from github: `devtools::install_github("dmurdoch/leaflet@crosstalk4")`. If you do not want to 
#' install this version, the `crosstalk` behavior will silently fail but your code will otherwise 
#' run just fine.
#' 
#' @param df `dataframe / tibble / datatable` Dataset of values for the choropleth.
#' @param x `list` Named list where keys are the columns of `df` to plot and the values are the 
#'   names to be used as the layer and legend titles.
#' @param date `date` Date to be plotted. If NULL, the most recent available date is used. Default 
#'   is NULL. Passed to [make_map_data()].
#' @param map `sf` A simple features dataset containing GIS data to join with df. Passed to 
#'   [make_map_data()]. 
#' @param id_label `chr` Column name in `df` to use as the shape name in the tooltip.
#' @param info_labels `list` Named list corresponding to the `df` columns (keys) and desired label 
#'   text (values) to appear in the tooltip. By default, the list `x` will be used.
#' @param palette `list` List of palettes to be used for the respective variables in x. The list 
#'   can be named to match the keys of x, if not the palettes will be taken in order. Palettes  
#'   should be a general palette name (eg: 'Blues'). In the case of factor variables, a vector 
#'   of specific colors can be given instead. **Note**: for factor variables, the variable itself
#'   must already be ordered in `df`, otherwise the factors will be ordered by appearance. If no
#'   palette is provided, 'Blues' will be used for every layer.
#' @param collapse_controls `bool` If True and if more than one layer is present (ie, if 
#'   `length(x) > 1`), then the layer control in the top right corner will be collapsed. Default is
#'   TRUE.
#' @param legend `bool` If True, the legend will be shown in the bottom right corner. Default is 
#'   TRUE.
#' @param legend_position `chr` The desired position of the legend. Default is 'bottomright'.
#' @param crosstalk `bool` If TRUE, the map data created and used will be converted into a 
#'   [crosstalk](https://rstudio.github.io/crosstalk/) `SharedData` object. **Note:** enabling 
#'   crosstalk is mutually exclusive to other aspects of `plot_leaflet`, in particular it cannot be
#'   used on maps with multiple layers or with the internal `custom_css` option (though custom css
#'   can still be added to the widget from a parent environment (ie rmarkdown or shiny). Default is 
#'   FALSE.
#' @param crosstalk_key `chr` If crosstalk is TRUE, `crosstalk_key` allows you to optionally 
#'   specify which column in `df` to use as the key for the SharedData. Default is NULL, meaning
#'   no key will be specified.
#' @param crosstalk_group `chr` If `crosstalk` is TRUE, `crosstalk_group` allows you to specify the
#'   group id name provided to `SharedData`. Default is NULL, meaning a random group name will be 
#'   generated by crosstalk.
#' @param ... Additional arguments to be passed to [make_leaflet_labels()]
#' 
#' @return `leaflet widget`
#' 
#' @examples
#' library(dplyr)
#' 
#' df_dep %>%
#'   group_by(dep) %>%
#'   mutate(p_evo = evolution(p)) %>%
#'   ungroup() %>%
#'   plot_leaflet(x = c(p = 'Cases',
#'                      pop = 'Population'),
#'                id_label = 'dep',
#'                evolution = c('p'))
#' 
#' 
#' @importFrom leaflet leaflet colorBin addPolygons labelOptions highlightOptions addLegend
#'   addLayersControl layersControlOptions colorFactor
#' @importFrom htmlwidgets onRender
#' @importFrom htmltools htmlDependency
#' @importFrom viridis viridis
#' @importFrom crosstalk SharedData
#' @importFrom rlang .data
#' @export
mod_plot_leaflet <- function(df, x, date = NULL, map = NULL, 
                             id_label = 1, info_labels = x,
                             palette = NULL, collapse_controls = FALSE,
                             legend = TRUE, legend_position = 'bottomright',
                             crosstalk = FALSE, crosstalk_key = NULL, crosstalk_group = NULL,
                             ...) {
  
  if (is.null(palette)) {
    palette <- rep('Blues', length(x))
  }

  if (is.null(names(palette))) {
    names(palette) <- names(x)
  }

  if (is.null(date) & 'date' %in% names(df)) {
    df <- df %>%
            filter(date == max(date))
  }

  data <- map %>%
            left_join(df,
                      sort = FALSE) %>%
            as('Spatial')

  labels <- make_leaflet_labels(data = data,
                                id_label = id_label,
                                info_labels = info_labels,
                                ...)

  # initialize shareddata object for crosstalk
  #if (crosstalk) {
    #if (is.null(crosstalk_key)) {
      #sd_data <- data %>%
                   #SharedData$new(group = crosstalk_group)
    #} else {
      #sd_data <- data %>%
                   #SharedData$new(key = ~.data[[crosstalk_key]], 
                                  #group = crosstalk_group)
    #}
  #} else {
    sd_data <- data
  #}


  m <- leaflet(sd_data)

  # build layers
  for (var in names(x)) {
    # define layer palette 
    if (is.numeric(df[[var]])) {
      pal <- colorBin(palette[[var]],
                      domain = data[[var]])
    } else {
      pal <- colorFactor(palette[[var]],
                         ordered = FALSE,
                         domain = data[[var]])
    }

    m <- m %>%
             addPolygons(group = x[[var]],
                         fillColor = ~pal(data[[var]]),
                         fillOpacity = 1,
                         color = 'black',
                         weight = 1,
                         label = labels,
                         labelOptions = labelOptions(textsize = '15px'),
                         highlightOptions = highlightOptions(weight = 5,
                                                             color = 'black')) %>%
             addLegend(group = x[[var]],
                       opacity = 1,
                       position = 'bottomleft',
                       title = x[[var]],
                       pal = pal,
                       values = ~data[[var]])
  }

  # enable legend to change with layer
  if (length(x) > 1) {
    m <- m %>%
      addLayersControl(baseGroups = unname(x),
                       options = layersControlOptions(collapsed = collapse_controls)) %>%
      htmlwidgets::onRender("
        function(el, x) {
          var updateLegend = function () {
              var selectedGroup = document.querySelectorAll('input:checked')[0].nextSibling.innerText.substr(1);
 
               document.querySelectorAll('.legend').forEach(a => a.hidden=true);
               document.querySelectorAll('.legend').forEach(l => {
                 if (l.children[0].children[0].innerText == selectedGroup) l.hidden=false;
               });
           };
           updateLegend();
           this.on('baselayerchange', e => updateLegend());
      }")
  }

  return(m)
}


#' Make leaflet tooltip labels
#' 
#' @description Build the html tooltip text.
#' 
#' @param data `spatial polygon dataframe` Merged map data.
#' @param id_label `chr` Column name in `df` to use as the shape name in the tooltip.
#' @param info_labels `list` Named list corresponding to the `df` columns (keys) and desired label 
#'   text (values) to appear in the tooltip. By default, the list `x` will be used.
#' @param decimals `int` Number of decimal places to be shown. Passed to [french_format()]. Default 
#'   is 0.
#' @param percent `chr vector` Vector listing the names of variables in `info_labels` to be 
#'   displayed as percents. Passed to [french_format()]. Note that [french_format()] assumes the 
#'   values are *proportions* not *percents* (ie, to get 43%, you must input 0.43 not 43). Default
#'   is an empty list.
#' @param evolution `chr vector` Vector listing the names of variables in `info_labels` to have 
#'   their evolution included in the tooltip. **Warning**, [make_leaflet_labels()] assumes that 
#'   these evolutions are already in `data` with column names conforming to the format {name}_evo. 
#'   Default is an empty list.
#' @param flip_colors `chr vector` Vector listing the names of variables in `info_labels` where 
#'   the default evolution colors should be inverted. Passed to [up_down_format()]. Default is
#'   an empty list.
#' 
#' @return `list`
#' 
#' @export 
make_leaflet_labels <- function(data, id_label = 1, info_labels,
                                decimals = 0, percent = c(),
                                evolution = c(), flip_colors = c()) {

  labels <- paste0('<i style="font-size:1.1em">', data[[id_label]], '</i>')

  for (i in names(info_labels)) {
    labels <- paste0(labels,
                     '<br>',
                     info_labels[[i]],
                     ': <b>',
                     lapply(data[[i]], 
                            function(x) tinker::french_format(x,
                                                              decimals = decimals,
                                                              percent = i %in% percent)),
                     '</b> ')

    if (i %in% evolution) {
      labels <- paste0(labels,
                       lapply(data[[paste0(i, '_evo')]],
                              function(x) tinker::up_down_format(x,
                                                                 flip_colors = i %in% flip_colors)))
    }
  }

  labels <- labels %>%
              lapply(htmltools::HTML)

  return(labels)
}


mod_plot_leaflet <- function() {
  tmp <- tbl %>%
           select(reg, zone, cases_4w, deaths_4w, trend, measles, rubella, prevent_score, 
                  status_outbreak) %>%
           mutate.(cases_4w = replace_na(cases_4w, 0),
                   cases_4w_bin = case_when(cases_4w == 0 ~ '0',
                                            cases_4w <= 20 ~ '1 - 20',
                                            cases_4w <= 50 ~ '21 - 50',
                                            cases_4w <= 100 ~ '51 - 100',
                                            cases_4w <= 150 ~ '101 - 150',
                                            cases_4w <= 200 ~ '151 - 200',
                                            cases_4w <= 250 ~ '201 - 250',
                                            TRUE ~ '250+'),
                   cases_4w_bin = factor(cases_4w_bin,
                                         levels = c('0',
                                                    '1 - 20',
                                                    '21 - 50',
                                                    '51 - 100',
                                                    '101 - 150',
                                                    '151 - 200',
                                                    '201 - 250',
                                                    '250+')),
                   cases_4w_bin = ordered(cases_4w_bin),
                   deaths_4w = replace_na(deaths_4w, 0),
                   deaths_4w_bin = case_when(deaths_4w == 0 ~ '0',
                                            deaths_4w <= 5 ~ '1 - 5',
                                            deaths_4w <= 10 ~ '6 - 10',
                                            deaths_4w <= 20 ~ '11 - 20',
                                            deaths_4w <= 30 ~ '21 - 30',
                                            deaths_4w <= 40 ~ '31 - 40',
                                            deaths_4w <= 50 ~ '41 - 50',
                                            TRUE ~ '50+'),
                   deaths_4w_bin = factor(deaths_4w_bin,
                                         levels = c('0',
                                                    '1 - 5',
                                                    '6 - 10',
                                                    '11 - 20',
                                                    '21 - 30',
                                                    '31 - 40',
                                                    '41 - 50',
                                                    '50+')),
                   deaths_4w_bin = ordered(deaths_4w_bin),
                   across.(c(measles, rubella),
                         ~ case_when(. == 0 ~ '0',
                                     . <= 2 ~ '1 - 2',
                                     . <= 4 ~ '3 - 4',
                                     . <= 6 ~ '5 - 6',
                                     . <= 8 ~ '7 - 8',
                                     . <= 10 ~ '9 - 10',
                                     . > 10 ~ '11+',
                                     TRUE ~ 'Pas d\'Echantion'),
                         .names = '{col}_bin'),
                   across.(c(measles_bin, rubella_bin), 
                   ~ factor(.,
                            levels = c('Pas d\'Echantion',
                                       '0',
                                       '1 - 2',
                                       '3 - 4',
                                       '5 - 6',
                                       '7 - 8',
                                       '9 - 10',
                                       '11+'))),
                   across.(c(measles_bin, rubella_bin),
                          ~ ordered(.)),
                   trend = factor(trend,
                                  levels = c('Pas des Données',
                                             'Baisse',
                                             'Stable',
                                             'Hausse')),
                   tend = ordered(trend),
                   trend_pop = as.character(trend),
                   status_outbreak = ifelse(status_outbreak == '', 'Pas d\'Alerte', status_outbreak),
                   status_outbreak = factor(status_outbreak,
                                            levels = c('Pas d\'Alerte',
                                                       'Suspecté',
                                                       'Confirmé')),
                   status_outbreak = ordered(status_outbreak),
                   prevent_score = as.character(prevent_score),
                   prevent_score = replace_na(prevent_score, 'Épidémie Suspectée'),
                   prevent_score = factor(prevent_score,
                                          levels = c('Épidémie Suspectée',
                                                     '0',
                                                     '1',
                                                     '2',
                                                     '3',
                                                     '4',
                                                     '5',
                                                     '6')),
                   prevent_score = ordered(prevent_score)
                   )
                                        
  legend <- list(status_outbreak = 'Alertes',
                 prevent_score = 'Score Prevention',
                 cases_4w_bin = 'Cas (4 Sem.)',
                 trend = 'Cas (Tendance)',
                 deaths_4w_bin = 'Décès (4 Sem.)',
                 measles_bin = 'Confirmations Rougeole',
                 rubella_bin = 'Confirmations Rubéole')

  info_pops <- list(status_outbreak = 'Alertes',
                    prevent_score = 'Score Prevention',
                    cases_4w = 'Cas (4 Sem.)',
                    trend = 'Cas (Tendance)',
                    deaths_4w = 'Décès (4 Sem.)',
                    measles = 'Confirmations Rougeole',
                    rubella = 'Confirmations Rubéole')

  lab_pal <- c('#ededed',
               '#EFF9F8',
               '#D4F0F0',
               '#B7E4E9',
               '#98D4E4',
               '#7D9FC0',
               '#636F9A',
               '#4C4975')


  palets <- list(status_outbreak = c('#ffffff',
                                     '#E6B8B3',
                                     '#755B58'),
                 prevent_score = c('#c5c5c5',
                                   '#FAF3F4',
                                   '#F2DFE1',
                                   '#ECCAC9',
                                   '#E6B8B3',
                                   '#C19994',
                                   '#9B7976',
                                   '#755B58'),
                 cases_4w_bin = c('#F8F7F3',
                                  '#ECEBDF',
                                  '#E2E1CA',
                                  '#D6D8B4',
                                  '#BCBE9D',
                                  '#A1A386',
                                  '#87886F',
                                  '#6C6D59'),
                 deaths_4w_bin = c('#F1F7F3',
                                   '#DAEAE0',
                                   '#C3DDCE',
                                   '#AAD2BF',
                                   '#94B8A7',
                                   '#7E9F8F',
                                   '#698577',
                                   '#546A60'),
                 trend = c('#ededed',
                           '#F8F7F3',
                           '#D6D8B4',
                           '#6C6D59'),
                 measles_bin = lab_pal,
                 rubella_bin = lab_pal)

  out_map <- render_map(tmp,
             x = legend,
             palette = palets,
             info_labels = info_pops,
             id_label = 'zone_display',
             map = drc) +
             

  out_map %>% saveRDS(here::here('out', 'country_map.RDS'))


# reg maps
tmp <- tbl %>%
				 select(reg, zone, cases_4w, deaths_4w, trend, measles, rubella, prevent_score, 
                status_outbreak) %>%
         mutate.(cases_4w = replace_na(cases_4w, 0),
                 cases_4w_bin = case_when(cases_4w == 0 ~ '0',
                                          cases_4w <= 20 ~ '1 - 20',
                                          cases_4w <= 50 ~ '21 - 50',
                                          cases_4w <= 100 ~ '51 - 100',
                                          cases_4w <= 150 ~ '101 - 150',
                                          cases_4w <= 200 ~ '151 - 200',
                                          cases_4w <= 250 ~ '201 - 250',
                                          TRUE ~ '250+'),
                 cases_4w_bin = factor(cases_4w_bin,
                                       levels = c('0',
                                                  '1 - 20',
                                                  '21 - 50',
                                                  '51 - 100',
                                                  '101 - 150',
                                                  '151 - 200',
                                                  '201 - 250',
                                                  '250+')),
								 cases_4w_bin = ordered(cases_4w_bin),
                 trend = factor(trend,
                                levels = c('Pas des Données',
                                           'Baisse',
                                           'Stable',
                                           'Hausse')),
                 trend = ordered(trend),
                 trend_pop = as.character(trend))

tmp_nat <- tbl %>%
				 select(reg, cases_4w) %>%
         group_by(reg) %>%
         summarize(cases_4w = sum(cases_4w))

legend <- list(trend = 'Cas (Tendance)',
               cases_4w_bin = 'Cas (4 Sem.)')

info_pops <- list(trend_pop = 'Cas (Tendance)',
                  cases_4w = 'Cas (4 Sem.)')

palets <- list(cases_4w_bin = c('#F8F7F3',
                                '#ECEBDF',
                                '#E2E1CA',
                                '#D6D8B4',
                                '#BCBE9D',
                                '#A1A386',
                                '#87886F',
                                '#6C6D59'),
               trend = c('#8f8f8f',
                         '#2E4172',
                         '#7887AB',
                         '#AA8439'))

reg_maps <- list()
for (r in unique(df$reg)) {
  writeLines(r)
  reg_maps[[r]] <- render_map(tmp %>% filter(reg == r),
                              x = legend,
                              palette = palets,
                              info_labels = info_pops,
                              id_label = 'zone_display',
                              map = drc %>% filter(reg == r))
}

tmp_nat <- df_nat %>%
             filter(date == max(date)) %>%
             mutate(reg = zone) %>%
             select(reg, trend) %>%
             right_join(tmp_nat) %>%
             mutate.(cases_4w = replace_na(cases_4w, 0),
                     cases_4w_bin = case_when(cases_4w == 0 ~ '0',
                                              cases_4w <= 25 ~ '1 - 25',
                                              cases_4w <= 50 ~ '26 - 50',
                                              cases_4w <= 100 ~ '51 - 100',
                                              cases_4w <= 200 ~ '101 - 200',
                                              cases_4w <= 500 ~ '201 - 500',
                                              cases_4w <= 1000 ~ '501 - 1000',
                                              TRUE ~ '1000+'),
                     cases_4w_bin = factor(cases_4w_bin,
                                           levels = c('0',
                                                      '1 - 25',
                                                      '26 - 50',
                                                      '51 - 100',
                                                      '101 - 200',
                                                      '201 - 500',
                                                      '501 - 1000',
                                                      '1000+')),
                     cases_4w_bin = ordered(cases_4w_bin),
                     trend = factor(trend,
                                    levels = c('Pas des Données',
                                               'Baisse',
                                               'Stable',
                                               'Hausse')),
                     trend = ordered(trend),
                     trend_pop = as.character(trend))
         
palets <- list(cases_4w_bin = c('#F8F7F3',
                                '#ECEBDF',
                                '#E2E1CA',
                                '#D6D8B4',
                                '#BCBE9D',
                                '#A1A386',
                                '#87886F',
                                '#6C6D59'),
               trend = c(#'#8f8f8f',
                         '#2E4172',
                         '#7887AB',
                         '#AA8439'))

reg_maps[['RDC']] <- render_map(tmp_nat,
                              x = legend,
                              palette = palets,
                              info_labels = info_pops,
                              id_label = 'reg_display',
                              map = drc_reg)

reg_maps %>% saveRDS(here::here('out', 'reg_maps.RDS'))

}
