---
title: "Scrollytelling"
output: 
  flexdashboard::flex_dashboard:
    self_contained: true
    vertical_layout: fill
    theme: lumen
---

```{r, echo=FALSE, comment=FALSE, warning=FALSE}
library(echarts4r)
library(tidyverse)
df <- Titanic
mtcars2 <- mtcars %>%
  #head() %>%
  tibble::rownames_to_column("model")
max <- list(
  name = "Max",
  type = "max"
)
min <- list(
  name = "Min",
  type = "min"
)
e01 <- mtcars2 %>% slice(1:2) %>%
  e_charts(model) %>% 
  e_title("Look at this nice circle,\ndevided into two parts.\n\nBut what is it?", top = 40) %>%
  e_grid(top = 100) %>% 
  e_x_axis(show = FALSE) %>%
  e_legend(show = FALSE, right = 10) %>%
   e_pie(
    qsec, label = list(show = FALSE), 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  )

e1 <- mtcars2 %>% slice(1:2) %>%
  e_charts(model) %>% 
  e_title("Pie chart alert!\n\nThese are 'qsec' scores of two cars\nBut okay, two categories... We will keep the pie...\n\nBut what if we add a car?\nIs the pie still readable...?", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_pie(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  )

e2 <- mtcars2 %>% slice(1:3) %>%
  e_charts(model) %>%
  e_title("Well I don't think so.\n\nI guess it all gets even worse if we add another car", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_pie(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  )

e3 <- mtcars2 %>% slice(1:4) %>%
  e_charts(model) %>%
  e_title("Yes... here you go :(.\n\nFor most people the pie fails to be easy to read.\n\nLet's turn it into a rose. Is that better?", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_pie(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  )

e4 <- mtcars2 %>% slice(1:4) %>%
  e_charts(model) %>%
  e_title("Yes, the rose type chart is way better to understand :).\n\nBut I am curious about how it looks like in a line chart.", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_pie(
    qsec, 
    roseType = TRUE,
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  )

e5 <- mtcars2 %>% slice(1:6) %>%
  e_charts(model) %>%
  e_title("Here's the line chart!\n\nNow the silly thing is that we connect cars by lines\nwhilst there is no connection at all\nthey are still categories.\n\nlet's turn it into a bar chart", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_line(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  ) %>% e_y_axis(show = FALSE)

e6 <- mtcars2 %>% slice(1:6) %>%
  e_charts(model) %>%
  e_title("yes, that's better!\n\nWe lost the colors though\n\n(ofcourse that can be done properly in echarts4,\nbut today I am lazy)", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_bar(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  ) %>% e_y_axis(show = FALSE)
e7 <- mtcars2 %>% slice(1:6) %>%
  e_charts(model) %>%
  e_title("By the way, here are the cars with\nlowest and highest scores.\n\nLet's add more cars!\nI am wondering which ones will be the lowest and hightest", top = 40) %>%
  e_grid(top = 100) %>%
  e_legend(right = 10) %>%
   e_bar(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  ) %>%
  e_y_axis(show = FALSE) %>%
  e_mark_point(data = max) %>%
  e_mark_point(data = min)

e8 <- mtcars2 %>% slice(1:20) %>%
  e_charts(model) %>% 
  e_title("Well.. for me this a nice final chart of this data story :)\n\nbye all!", top = 40) %>%
  e_grid(top = 200, bottom = 100) %>%
  e_legend(right = 10) %>%
   e_bar(
    qsec, 
    universalTransition = TRUE,
    animationDurationUpdate = 1000L
  ) %>%
  e_x_axis(axisLabel = list(rotate = 30)) %>%
  e_y_axis(show = FALSE) %>%
  e_mark_point(data = max) %>%
  e_mark_point(data = min)



cb <- "() => {
  let x = 0;
  document.getElementById('toggle')
    .addEventListener('click', (e) => {
      x++
      chart.setOption(opts[x % 9], true);
    });
}"

e_morph(e01, e1, e2, e3,e4, e5, e6,e7,e8,callback = cb) %>% 
  htmlwidgets::prependContent(
    htmltools::tags$button("Continue telling!", id = "toggle")
  )
